# Generated by Django 5.0 on 2023-12-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0013_about_delete_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='image_2',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип'),
        ),
    ]
