# Generated by Django 5.0 on 2023-12-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0017_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='descriptions1',
            field=models.CharField(max_length=500, verbose_name='Описание 1'),
        ),
        migrations.AlterField(
            model_name='values',
            name='descriptions2',
            field=models.CharField(max_length=500, verbose_name='Описание 2'),
        ),
        migrations.AlterField(
            model_name='values',
            name='descriptions3',
            field=models.CharField(max_length=500, verbose_name='Описание 3'),
        ),
    ]
