# Generated by Django 5.0 on 2023-12-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0020_junior_alter_values_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': ('Портфолио',),
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.AlterModelOptions(
            name='junior',
            options={'verbose_name': ('Junior',), 'verbose_name_plural': 'Junior'},
        ),
    ]
