# Generated by Django 5.0 on 2023-12-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0021_portfolio_alter_junior_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='descriptions',
        ),
    ]
