# Generated by Django 5.0 on 2023-12-08 13:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0022_remove_portfolio_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='blog_image/', verbose_name='Фотография')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': ('Контакт',),
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
